[package]
name = "miMusic"
version = "0.1.0"
edition = "2024"

[dependencies]
id3 = "1.16.2"
ratatui = "0.29.0"
rodio = { version = "0.20.1", default-features = false, features = ["symphonia-mp3"] }
symphonia = { version = "0.5.4", features = ["mp3"] }
walkdir = "2.5.0"
yt-dlp = "1.3.4"
