name: Building miMusic

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Pre-installation
      run: sudo apt-get install libasound2-dev
    - name: Rust toolchain version to nightly
      run: rustup default nightly
    - name: Build API
      run: cargo build --bin api --verbose
    - name: Build miMusic
      run: cargo build --bin miMusic --verbose
    - name: Run miMusic
      run: cargo run --bin miMusic
